spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-group
      auto-offset-reset: earliest
  main:
    web-application-type: reactive

server:
  port: 8080 

logging:
  level:
    org.apache.kafka: DEBUG
    reactor.kafka: DEBUG 